src/Entity/Project.php
src/Entity/User.php
src/Library/Benzina/Pump/ProjectsPump.php

Added a new `Pump` implementation to process project records from a v3 database.
Updated the Project entity with minimum data. It will be necessary to discuss and fully update this entity with the remaining fields.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206886898548701

v3 project migration

---

.env
composer.json
composer.lock
config/services.yaml
src/Controller/GatewayController.php
src/Entity/GatewayCharge.php
src/Library/Economy/Payment/GatewayInterface.php
src/Library/Economy/Payment/StripeGateway.php
src/State/GatewayCheckoutProcessor.php

This PR allows v4 to process `GatewayCharges` and `GatewayCheckouts` via Stripe.

[feat] Add Stripe payment gateway

---

src/Library/Benzina/Pump/CheckoutsPump.php

Fixes outdated `GatewayCheckout` usage in `CheckoutsPump`.
See https://github.com/GoteoFoundation/v4/pull/26

Add GatewayTracking to CheckoutsPump

---

tests/Entity/Accounting/AccountingTest.php
tests/Entity/ProjectApiTest.php
tests/Library/Economy/MoneyServiceTest.php

Improve tests coverage for some common cases that were being unnecessarily tested manually.

[feat] Improve tests coverage

---

src/Library/Economy/Currency/EuropeanCentralBankExchange.php
src/Library/Economy/Currency/ExchangeInterface.php
src/Library/Economy/Currency/ExchangeLocator.php
src/Library/Economy/MoneyService.php

Small code improvements and updates to the Exchange scope.

[feat] Update exchanges

---

config/services.yaml
src/Mapping/AutoMapper.php

Small performance and DX improvements.

[feat] Mapper improvements

---

.github/workflows/phpunit.yaml
config/services.yaml
src/ApiResource/Accounting/AccountingApiResource.php
src/ApiResource/Gateway/CheckoutApiResource.php
src/Entity/Gateway/Charge.php
src/Entity/Gateway/Checkout.php
src/Gateway/Stripe/StripeGateway.php
src/Mapping/AutoMapper.php
src/Mapping/Transformer/AccountingBalanceMapTransformer.php
src/Mapping/Transformer/GatewayNameMapTransformer.php
src/State/Accounting/AccountingStateProvider.php

[fix] State stack and data mappings

---

src/ApiResource/Project/ProjectApiResource.php
src/ApiResource/User/UserTokenApiResource.php
src/Entity/Interface/UserOwnedInterface.php
src/Entity/Project/Project.php
src/Entity/Project/RewardClaim.php
src/Entity/Trait/UserOwnedTrait.php
src/Entity/User/UserToken.php
src/Security/Voter/AccountingVoter.php
src/Security/Voter/ProjectVoter.php
src/Security/Voter/UserOwnedVoter.php
src/Security/Voter/UserOwnedVoterTrait.php
src/Security/Voter/UserVoter.php

Several fixes and improvements related to the security layer, mainly:

[fix] User owned security

---

src/ApiResource/Project/ProjectApiResource.php
src/ApiResource/User/UserApiResource.php
src/Dto/UserSignupDto.php
src/Entity/User/User.php
src/Security/Voter/UserVoter.php
src/State/User/UserSignupProcessor.php

This PR allows to finish the user sign up flow, which was half-way done.

[chore] Update flows

---

bin/docker
src/ApiResource/Accounting/TransactionApiResource.php
src/ApiResource/Gateway/CheckoutApiResource.php
src/Entity/Accounting/Accounting.php
src/Entity/Accounting/Transaction.php
src/Entity/Gateway/Checkout.php
src/Gateway/AbstractGateway.php
src/Gateway/Paypal/PaypalGateway.php
src/Gateway/Stripe/StripeGateway.php
src/Service/Gateway/CheckoutService.php
src/State/User/UserSignupProcessor.php

Small bugfixes and improvements on the checkout flow and accounting data exposure:

[fix] Checkout flow

---

src/Gateway/Stripe/StripeGateway.php

[fix] Improve stripe usage

---

src/OpenApi/OpenApiFactory.php
src/OpenApi/OpenApiMetadataTrait.php
src/OpenApi/RedocExtensionsTrait.php
templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig

[chore] OpenAPI updates

---

src/ApiResource/LocalizedApiResourceTrait.php
src/ApiResource/Project/BudgetItemApiResource.php
src/ApiResource/Project/ProjectApiResource.php
src/ApiResource/Project/UpdateApiResource.php
src/Entity/Project/Project.php
src/Entity/Project/Update.php
src/OpenApi/RedocExtensionsTrait.php
src/Repository/Project/UpdateRepository.php

Add a new resource `ProjectUpdate` to allow Projects to post small news on their campaign page.

[feat] Project updates

---

composer.json
composer.lock
src/Benzina/CheckoutsPump.php
src/Benzina/DatabasePumpTrait.php
src/Benzina/ProjectsBudgetPump.php
src/Benzina/ProjectsPump.php
src/Benzina/ProjectsRewardsPump.php
src/Benzina/UsersPump.php
src/Entity/Project/Project.php

Upgraded to benzina 0.4 which shares pumping context with the pump instances and makes use of it to retrieve external data at the same time it pumps one table, specifically the milestones and blog posts table records for projects.

[chore] Benzina updates

---

src/ApiResource/Accounting/AccountingApiResource.php
src/ApiResource/User/UserApiResource.php
src/Security/Voter/AccountingVoter.php
src/Security/Voter/UserVoter.php

Updates on the visibility of resource properties.
- User email related info only visible to admins and the user themselves.
- Accounting balance of users only visible to admins and the user themselves.
- Accounting balance of projects visible to everyone.

[fix] Properties visibility

---

src/ApiResource/Project/ProjectApiResource.php
src/Benzina/ProjectsPump.php
src/Entity/Project/Category.php
src/Entity/Project/Project.php
tests/Entity/ProjectApiTest.php

Adds concept of `category` to Project resources, using the categories from the research done in https://journal.platoniq.net/en/wilder-journal-1/futures/nature-sdg-in-goteo/

[feat] Project categories

---

src/ApiResource/Project/SupportApiResource.php
src/Entity/Accounting/Accounting.php
src/Entity/Gateway/Charge.php
src/Entity/Project/Project.php
src/Entity/Project/Support.php
src/Entity/Trait/UserOwnedTrait.php
src/Entity/User/User.php
src/OpenApi/RedocExtensionsTrait.php
src/Repository/Project/SupportRepository.php
src/Security/Voter/SupportVoter.php
src/State/Project/SupportStateProcessor.php

Added a `ProjectSupport` resource to the API that relates charges made by an User to a Project.

[feat] ProjectSupport resources

---

tests/Entity/ProjectCalendarTest.php

When running the tests, deprecation warnings related to the use of ArrayAccess in embedded classes of Doctrine appear. The message is:
"Using ArrayAccess on Doctrine\ORM\Mapping\EmbeddedClassMapping is deprecated and will not be possible in Doctrine ORM 4.0."
It seems the solution would be to stop using ArrayAccess and access the properties directly. This change involves other classes and would affect other parts of the code, so I haven't considered it a priority since it's just a warning. Just wanted to bring it to your attention.

GV4-050 Functional tests project calendar

---

src/ApiResource/Gateway/CheckoutApiResource.php
src/Dto/CheckoutUpdationDto.php
src/Entity/Gateway/Checkout.php
src/Gateway/RefundStrategy.php
src/Security/Voter/CheckoutVoter.php
src/Security/Voter/UserOwnedVoterTrait.php
src/State/Gateway/CheckoutStateProcessor.php

[feat] Add Checkout patching

---

src/Gateway/Wallet/WalletGateway.php
src/Security/Voter/UserOwnedVoterTrait.php

[fix] Checkout with Wallet

---

.github/workflows/db-dump.yaml

This workflow allows dumping the Goteo v4 database for the current environments (prod, staging, and testing).

Add db dump workflow
